### ISSUE TITLE
Make the i2c bus configurable

### ISSUE THREAD

**Issue by JasperWallace** [dhhagan/python-hih6130#2]
I'm not sure what drive the i2c bus numbering on RPI's, but some have an i2c-0 and some have an i2c-1

Could you add a bus argument to the constructor (defaulting to 1 so the behaviour dosen't change) and then pass it to the smbus constructor here:

https://github.com/dhhagan/python-hih6130/blob/master/HIH6130/io.py#L18

(posting this in a rush atm, will do a pull request when i get a chance, it's a tiny change tho).

**Comment by dhhagan** [comment]
Awesome @JasperWallace I'll take a look/merge whenever you send the PR!

**Comment by dhhagan** [comment]
Closed with PR#6
